### ISSUE TITLE
Youtube is showing already watched video in search result list

### ISSUE THREAD

**Issue by bitgub1** [Mandrenkov/FreshView#10]
![image](https://github.com/Mandrenkov/FreshView/assets/84478104/8049391c-ab57-484a-a90e-b4029362b2c2)
The red bar below the middle video shows that it is already watched.
Chrome Version 115.0.5790.173 (Officiell version) (64 bitar)
Win 10

**Comment by Mandrenkov** [comment]
Hi @bitgub1, thanks for submitting an issue! Unfortunately, I am no longer maintaining this project. Feel free to clone this repository and implement a fix locally if it suits your needs.
