### ISSUE TITLE
Hide videos you can't currently see

### ISSUE THREAD

**Issue by WitekS** [Mandrenkov/FreshView#2]
I have a question, can you consider adding options to hide videos scheduled for later? More info here
[https://github.com/OsaSoft/youtube-better-subscriptions/issues/68](url)

**Comment by Mandrenkov** [comment]
While I agree that it would be *useful* to optionally hide YouTube Premieres, I actually think it falls outside the current scope of the extension.  Ultimately, FreshView is about hiding videos you've already watched, but not necessarily those videos which you probably aren't interested in watching now (e.g., Premieres, something in your Watch Later playlist, etc.).

I know this is a frustrating response, but the truth is that there are several other features which are more relevant to the central goal of FreshView (e.g., keyboard shortcuts) that I'll need to consider first before broadening the scope of the extension into something like Better Subscriptions.  Once I get around to designing a UI for showing additional toggles, I think that hiding YouTube Premieres will be low-hanging fruit; however, this is FreshView v2.0.0 territory.

**Comment by Mandrenkov** [comment]
Given that a year has passed, I am going to close this issue unless there is more demand for this feature.
