### ISSUE TITLE
Add option to disable FreshView on specific pages

### ISSUE THREAD

**Issue by Mandrenkov** [Mandrenkov/FreshView#3]
> Any chance you could allow users to exclude certain URLs? For example, if I want to cleanup my "watch later" list (manually remove videos that I've watched), I have to disable your extension every time in order to see the full list. It would be nice if a user could exclude certain youtube pages like "watch later" list. Just a suggestion for future feature...

**Comment by juhana** [comment]
I think all playlists (including "Watch later") should be excluded by default. Most of the time you make playlists for videos that you have watched and actually want to watch again later. Now you have to manually toggle the extension on and off when going through your own playlists to see their full contents.

Also, the Library page (https://www.youtube.com/feed/library) hides fully watched videos in history even though the actual History page doesn't so it should be excluded as well.

**Comment by Mandrenkov** [comment]
Thanks for pointing this out!  Once I finish updating the UI, I'll add a set of controls to disable FreshView in the "Water later" and "Liked videos" playlists (and fix the "History" bug in the Library page).
