### ISSUE TITLE
The extension stopped working for me after latest changes on YouTube

### ISSUE THREAD

**Issue by joonaskokko** [Mandrenkov/FreshView#6]
For the last week the extension has stopped filtering out viewed videos. This seems to be bundled with some changes made on YouTube's end.

<img width="723" alt="Screenshot 2021-11-30 at 23 50 48" src="https://user-images.githubusercontent.com/24448/144133784-5e29dbdc-ae15-4a26-8c77-b3fc79ba49e5.png">

**Comment by Mandrenkov** [comment]
Thanks for letting me know about this, @joonaskokko!

Commit 174144401932ad973805e0289607c3e85705dde6 addresses this issue and is included as part of the v2.0.4 release.

**Comment by joonaskokko** [comment]
Thanks a lot!
